### ISSUE TITLE
useStdoutDimensions gives error on importing.

### ISSUE THREAD

**Issue by schu34** [cameronhunter/ink-monorepo#1]
when I run my application that imports the hook I get this error 
```
Error: Cannot find module '/Users/matthewschupack/dev/npm-search/node_modules/ink-use-stdout-dimensions/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:300:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:531:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/matthewschupack/dev/npm-search/build/index.js:7:54)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/matthewschupack/dev/npm-search/node_modules/ink-use-stdout-dimensions/package.json',
  requestPath: 'ink-use-stdout-dimensions'
```

When I navigate to `node_modules/ink-use-stdout-dimensions` and `ls` I get 
```
LICENSE.md   package.json   README.md
```
(no src or build directory)

**Comment by cameronhunter** [comment]
Arg, yeah, sorry about that. It's fixed in `v1.0.5`.
